baseURL = "https://vertcoin.org/"
DefaultContentLanguage = "en"
title = "Vertcoin"
theme = "elate"


#This file prints out code blocks



#Language


   [languages]
   
  [languages.en]
    languageName = "English"
    weight = 1
    url = "/"
    
  [languages.fr]
    
    languageName = "Français"
    weight = 2
    url = "/fr"

  [languages.ja]
    
    languageName = "日本語"
    weight = 3
    url = "/ja"


  [languages.cn]
    
    languageName = "中文"
    weight = 4
    url = "/cn"

    

  [languages.ko]
    languageName = "한국의"
    weight = 5
    url = "/ko"


    
   
[languages.es]
    languageName = "Español"
    weight = 6
    url = "/es"

    [languages.nl]
    languageName = "Nederlands"
    weight = 7
    url = "/nl"


  [languages.cz]
    languageName = "Čeština"
    weight = 8
    url = "/cz"


[languages.ru]
    languageName = "Русский"
    weight = 9
    url = "/ru"


[languages.de]
    languageName = "Deutsch"
    weight = 10
    url = "/de"

  

[languages.ar]
    languageName = "العربية"
    weight = 11
    url = "/ar"


    

    






# Menu

[[menu.main]]
url = "/merchants/"
name = "merchants"
weight = 5

[[menu.main]]
url = "/trading/"
name = "trading"
weight = 7

[[menu.main]]
url = "/mine/"
name = "mine"
weight = 9

[[menu.main]]
url = "/community/"
name = "community"
weight = 11





	
	

#Parameters


[params]




  [params.navigation]


  [params.action]

    [[params.navigationAction.item]]


  [params.desktopDownload]


    [[params.desktopButton.item]]







# quickOverview 

[params.quickOverview]
    [[params.quickOverview.item]]
    url = "/vertcoin-for-individuals"
    [[params.quickOverview.item]]
     url = "/vertcoin-for-businesses"
    [[params.quickOverview.item]]
    url = "/vertcoin-for-developers"


# litPoints

[params.litPoints]
    [[params.litPoints.item]]
    [[params.litPoints.item]]
    [[params.litPoints.item]]


# litboxPoints 

[params.litboxPoints]
    [[params.litboxPoints.item]]
    [[params.litboxPoints.item]]
    [[params.litboxPoints.item]]




# litLinks

    [params.litLinks]
    [[params.litLinks.item]]
    url = "https://github.com/mit-dci/lit"
    target = "_blank"
  

# Adoption Links

    [params.adoption]
    [[params.adoption.item]]
    url = "https://bitcoinmagazine.com/articles/history-lightning-brainstorm-beta/"
    target = "_blank"




# Values

 [params.values]
    [[params.values.item]]
    [[params.values.item]]
    [[params.values.item]]



   



 # About Section

  [params.about]

    [[params.about.item]]
      name = "Vertcoin Community"
      img = "placeholder.png"
      alt = "Community"
      social = [
            ["icon-reddit", "https://reddit.com/r/vertcoin"],
            ["icon-twitter", "https://twitter.com/vertcoin"],
            ["icon-discord", "https://discord.gg/vertcoin"],
            ["icon-github", "https://github.com/vertcoin-project"]
      ]


    [[params.about.item]]
      name = "James Lovejoy"
      img = "james.jpg"
      alt = "James Lovejoy"
      social = [
        ["icon-twitter", "https://twitter.com/jamesl22"],
        ["icon-github", "https://github.com/metalicjames/"],
        ["icon-linkedin", "https://www.linkedin.com/in/james-lovejoy-48ab16131/"]
      ]

    [[params.about.item]]
      name = "Joe Straub"
      img = "joe.jpg"
      alt = "Zemrys"
      social = [
        ["icon-github", "https://github.com/zemrys"]
      ]

    [[params.about.item]]
      name = "Eric Kubik"
      img = "eric.png"
      alt = "Eric"
      social = [
        ["icon-twitter", "https://twitter.com/etang600"]
      ]

    [[params.about.item]]
      name = "Star Im"
      img = "star.jpg"
      alt = "Star"
      social = []


    [[params.about.item]]
      name = "Gert-Jaap Glasbergen"
      img = "gertjaap.jpg"
      alt = "Gert-Jaap Glasbergen"
      social = [
        ["icon-twitter", "https://twitter.com/gertjaap"],
        ["icon-github", "https://github.com/gertjaap"],
        ["icon-linkedin", "https://www.linkedin.com/in/gertjaap"]
      ]

    [[params.about.item]]
      name = "Alex Turek"
      img = "person1.png"
      alt = "Alex Turek"
      social = [
        ["icon-linkedin", "https://www.linkedin.com/in/turekaj/"]
      ]

    [[params.about.item]]
      name = "jk_14"
      img = "person1.png"
      alt = "jk_14"
      social = []

    [[params.about.item]]
      name = "pknight"
      img = "person2.png"
      alt = "pknight"
      social = []


    [[params.about.item]]
      name = "Daiki"
      img = "daiki.jpg"
      alt = "Daiki"
      social = []


     [[params.about.item]]
      name = "CryptoPlankton"
      img = "person2.png"
      alt = "CryptoPlankton"
      social = [
        ["icon-twitter", "https://twitter.com/cryptoplankto"],
      ]


      
      [[params.about.item]]
      name = "Suriyaa Sundararuban"
      img = "person2.png"
      alt = "Suriyaa"
      social = [
        ["icon-twitter", "https://twitter.com/SuriyaaKudoIsc"],
        ["icon-github", "https://github.com/SuriyaaKudoIsc"],
        ["icon-linkedin", "https://www.linkedin.com/in/suriyaakudo/"]
      ]

    




 [params.contact]




  [params.footer]
    enable = true
    copyright = ''


